dist: trusty
sudo: required
addons:
    postgresql: "9.5"
before_script:
  - sudo psql -U postgres -c "ALTER USER postgres WITH PASSWORD 'sabha123'"
  - sudo psql -U postgres -c 'CREATE DATABASE tournaments'

language:
    java
jdk:
    - oraclejdk8
env:
    - TERM=dumb
script:
    - gradle clean build sonarqube
after_success:
    - gradle cobertura coveralls
